### ISSUE TITLE
Return empty reference prices if price feed not responding for long time

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-analytics#30]
Clients using gRPC  get randomly the below error calling the MarketPrice endpoint

```
{
  "error": "full url: https://tdexa.tdex.network:443/tdexa.v1.Analytics/MarketsPrices, code: 13, err: error code: 1015"
}
```

**Comment by tiero** [comment]
cc/ @sekulicd any ideas?

**Comment by sekulicd** [comment]
Do we have exact request that failed? @tiero

**Comment by IlSassone** [comment]
The request body was
```
{
  "time_range": {
    "predefined_period": 2
  },
  "market_ids": [
    "1", "6", "5", "2"
  ],
  "reference_currency": "eur",
  "page": {
    "page_size": 288
  }
}

```

**Comment by sekulicd** [comment]
Could be maybe related to rate limit error by external exchange rate api.

**Comment by tiero** [comment]
Would be best to catch this? Maybe best to return anyway data we have, to prevent external dependency halt our response? eventually we can return the reference price converted empty when it happens?

**Comment by sekulicd** [comment]
@tiero yeah, lets refactor a bit this by having some cache of prices from which we will fetch data and refresh it periodically.

**Comment by tiero** [comment]
> @tiero yeah, lets refactor a bit this by having some cache of prices from which we will fetch data and refresh it periodically.

**Comment by tiero** [comment]
> @tiero yeah, lets refactor a bit this by having some cache of prices from which we will fetch data and refresh it periodically.

I think it's important having not huge window of refresh: if happens a cached price too "old" (like more than 5 minutes?) best to return empty, than a wrong/old price

**Comment by tiero** [comment]
Would you take this? @altafan
