### ISSUE TITLE
5 minutes Custom Period

### ISSUE THREAD

**Issue by andreazllin** [tdex-network/tdex-analytics#49]
I am encountering this error when calling tdex-analytics `/marketsPrices` 
`INTERNAL: timeFrame must be smaller than timePeriod`

This is the request that fails:
```json
{
  "time_range": {
    "custom_period": {
      "end_date": "2022-11-08T09:16:35.600Z",
      "start_date": "2022-11-08T09:11:35.600Z"
    }
  },
  "market_ids": [
    "1", 
    "2",
    "3", 
    "4",
    "5",
    "6"
  ],
  "reference_currency": "usd",
  "page": {
    "page_number": 0,
    "page_size": 20
  },
  "time_frame": 0
}
```
`timeFrame` is 0 so it should be `TF_NULL`

From what I've been told tdex-analytics uses internally uses `nil` = `5 minutes`, so the error is thrown when `timeFrame` is grater than or equal to `timePeriod`, in this case `customPeriod`, 5 minutes

**Comment by altafan** [comment]
cc @sekulicd
