### ISSUE TITLE
Support fetching the spot price via new GetMarketPrice exposed by tdex trade protocol

### ISSUE THREAD

**Issue by tiero** [tdex-network/tdex-analytics#52]
Instead of hardcoding the amount sats and using `PreviewTrade` let's move to `GetMarketPrice` which returns the spot_price (ie. equivalent of quote_price) and the minimum tradeable amount needed to have a value that makes sense.

Need this to be merged https://github.com/tdex-network/tdex-daemon/pull/669 and deployed on mainnet daemons

**Comment by altafan** [comment]
Now that the PR has been merged, this service should try to call the GetMarketPrice API to fetch the spot price first and fallback to trade preview only if this endpoint is not avaiable.

**Comment by tiero** [comment]
Let's tag a v0.9 release for tdex daemon, and upgrade all the testnet providers. Also, let's update the mapping for `ASSET_CURRENCY_PAIRS` for USDQ and EURQ in the testnet instance on our infrastructure
