### ISSUE TITLE
New LAST_YEAR predefined period

### ISSUE THREAD

**Issue by altafan** [tdex-network/tdex-analytics#55]
We are missing a predefined period to for the last year. Currently, we have only YEAR_TO_DATE which covers the period from the beginning of the year to the current date, but it's not really the same thing.

**Comment by sekulicd** [comment]
Currently we have bellow predefined time ranges:
```
LAST_HOUR = 1;
LAST_DAY = 2;
LAST_MONTH = 3;
LAST_3_MONTHS = 4;
YEAR_TO_DATE = 5;
ALL = 6;
```
Do we need new one LAST_YEAR considering we have:
```
message CustomPeriod {
  // start_date in RFC3339 format
  string start_date = 1;
  // end_date in RFC3339 format
  string end_date = 2;
}
```

@tiero @altafan ?
